version: '3.8'

services:
  # Service MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: devops
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  # Service de votre application Spring Boot
  app:
    image: devops_project:1.0.jar
    build: .
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: devops
      SPRING_DATASOURCE_PASSWORD: devops

volumes:
  mysql_data:
