version: "3.9"
services:
  invoice:
    build: .
    ports:
      - "8070:8070"
    image: "mouhamedabbassii/invoice:vrs1"
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldatabase
    image: mysql:8
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - 3360:3360
    environment:
      MYSQL_DATABASE: invoicedb
      MYSQL_ROOT_PASSWORD: root