FROM node:18.18.1 as builder

WORKDIR /app

COPY . /app

RUN npm uninstall -D angular-cli --legacy-peer-deps

RUN npm install --force

FROM nginx:latest

COPY --from=builder /app/dist/summer-workshop-angular /usr/share/nginx/html

EXPOSE 4200
